### PR TITLE
add preserve attribute to settings

### PR DESCRIPTION
**Pull request by TomBruyneel**
Solves a problem with the linker when set to full linking. The dependency service could no longer resolve the settings class, this is solved by adding the preserve attribute

### CODE REVIEW

**Comment by baskren** [comment]
@TomBruyneel 

Upon first run, looks like this might be breaking a lot of functional tests.  Won't be in the NuGet release for a while.

**Comment by TomBruyneel** [comment]
It really shouldn't, that attribute does nothing except when the linker is doing its work. But if I find time I might take a look at it :)

**Comment by baskren** [comment]
For the sake of documenting this, the following tests were broken with Link All (vs Link Framework SDKs only):

- User Pages / MFoster Button Binding Sample : No buttons are changing state as a result of clicking the [Toggle State] button;
- User Pages / MFloyd : Xamarin.Forms.Xaml.XamlParseException, Cannot assign property "ColumnSpacing";
- User Pages / SegmentBindingPage: Text and images are missing from shaded cells;
- User Pages / XAML: F9P Label in Xamarin.ListView: frames in cells are missing background color;
- User Pages / ChatListPage: Bubbles not sized correctly and contains no text;
- Code / Picker in popup: Activation exception thrown;
- ListView Sandbox: Activation exception thrown;

There is also a suite of apps I maintain that I use as a second set of tests.  It has some really nasty use cases that seem to ferret out a lot of issues.  I haven't tested against those as it usually takes a day or so.

**Comment by baskren** [comment]
I fogot to mention that the above tests were run on iOS.  Haven't tried UWP or Android yet.  Also, in case it wasn't clear, the tests are in the Demo app: https://github.com/baskren/Forms9Patch/tree/master/Demo

**Comment by TomBruyneel** [comment]
Ah yes, as said, I solved my problem to start with. I thought you meant I broke something in sdk only linker mode. But those are interesting results and I'm willing to help you resolve some of them

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by baskren** [comment]
Yes ... any help you can give would be GREATLY appreciate.  I just made a commit to master (I should have branched it) that updates the test cases for Link All.  The last two issues I think are related and I'm going to look at them now.  If you do have any time to look at the first 5 issues, that would be most helpful!

**Comment by baskren** [comment]
Moving this thread to Issue #63

**Pull request merged**
