### PR TITLE
Made PageMargin creatable from library client code via factory methods

### PR DESCRIPTION
**Pull request by smalgin**

### CODE REVIEW

**Comment by smalgin** [comment]
Finally managed to build f9p locally (excluding IOS as I don't have Mac and UWP which  threw an error about missing AudioService & HapticService.

Last commit addresses syntax error while building.

**Comment by smalgin** [comment]
cc @baskren

**Comment by baskren** [comment]
@smalgin 

Sorry for taking so long to get to this.  Thanks for submitting. 

I'm about to do an update.  Will be releasing an update with this merge later today.

Good for you for getting F9P to build!  I've really put a lot of work in to enable others to do that.

Really strange that you got a syntax error with code in question.

**Comment by smalgin** [comment]
Hi. 

I was not able to get it fully built, I had to unload all IOS projects as the (Gestures AFAIR) package was not found. 
I believe that one got fixed based on the notifications I received recently. 👍 

Yes I got syntax error on ctor initializer with Left = Right = value; I was too busy to investigate why, sorry, too many fires to fight.
For the record, I have VS 2019 community, latest edition and Win 10 Pro - nothing out of ordinary.
Most importantly, I got it built. 

Btw I checked your carpentry app and it is a nice piece of work. I am kind of upset I don't have any practical reason to install it :)
(I hate computational geometry so I am naturally envious of any code that shows nice dynamically generated blueprints)

**Comment by baskren** [comment]
Thanks for the quick response.  The carpentry app will be 10 years old in a month.  Can't believe it!  I do a lot of engineering / construction projects these days - all because of that app!

**Pull request merged**
