### PR TITLE
Make TintColor work for SVG images

### PR DESCRIPTION
**Pull request by boris-gutman**
The proposed patch makes TintColor work for SVG images.

### CODE REVIEW

**Comment by baskren** [comment]
Cool!  I’m not sure I’ll be able take a look at it in the next couple weeks.  But looking forward to seeing it!

**Comment by baskren** [comment]
version 2.4.2 has this pull request.

**Comment by boris-gutman** [comment]
Wow, that was fast ))
Thank you for a great library!

**Comment by baskren** [comment]
@boris-gutman 

I need to thank you.  It is EXTREMELY rare for someone to provide me a pull request.  It's even rarer when they hadn't bothered to submit an issue.  THANK YOU!

**Comment by boris-gutman** [comment]
Glad to contribute, even if it's just 2 lines of code I found on StackOverflow :)

**Pull request merged**
